name: Despliegue en dos instancias EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Construir y empujar imagen Docker
        run: |
          docker build -t stalinvasco2024/dockerphp:tagname .
          docker push stalinvasco2024/dockerphp:tagname
      - name: Desplegar en instancia 1
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST_DNS}}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            # Actualizar el sistema y Docker
            sudo apt-get update -y
            sudo apt-get install -y docker.io

            # Detener y eliminar contenedores antiguos
            sudo docker stop my_container || true
            sudo docker rm my_container || true

            # Descargar la última imagen de Docker Hub
            sudo docker pull stalinvasco2024/dockerphp:tagname

            # Levantar el contenedor Docker y lo expone al puerto 80
            sudo docker run -d -p 80:80 --name my_container stalinvasco2024/dockerphp:tagname

            # Verificar que el contenedor se está ejecutando
            sudo docker ps
      - name: Desplegar en instancia 2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST2_DNS}}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            # Actualizar el sistema y Docker
            sudo apt-get update -y
            sudo apt-get install -y docker.io

            # Detener y eliminar contenedores antiguos
            sudo docker stop my_container || true
            sudo docker rm my_container || true

            # Descargar la última imagen de Docker Hub
            sudo docker pull stalinvasco2024/dockerphp:tagname

            # Levantar el contenedor Docker y lo expone al puerto 80
            sudo docker run -d -p 80:80 --name my_container stalinvasco2024/dockerphp:tagname

            # Verificar que el contenedor se está ejecutando
            sudo docker ps