name: Deploy PHP Project PROD

on:
  pull_request:
    branches:
        -main

jobs:
  update_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: stalinvasco2024/dockerphp:latest

  deploy:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: update_docker_image

    strategy:
      matrix:
        ec2_instance: 
          - ec2-100-25-138-65.compute-1.amazonaws.com
          - ec2-18-232-60-144.compute-1.amazonaws.com

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ matrix.ec2_instance }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop html_project || true
            sudo docker rm html_project || true
            sudo docker pull stalinvasco2024/dockerphp:latest
            sudo docker run -d --name html -p 80:80 stalinvasco2024/dockerphp:latest